### ISSUE TITLE
Request for "Delete All Temp Files" Command for the plugin

### ISSUE THREAD

**Issue by devangtomar** [wtetsu/vscode-tempfile#3]
Currently, the extension generates temporary files whenever a specific action is performed. However, there is no built-in option to delete all these temporary files at once.

I would like to suggest adding a new command to the command palette that allows users to delete all the generated temporary files in one go. This would greatly enhance the usability of the plugin and help keep the workspace clean as these `tempfiles` shows up in the file switcher.

<img width="598" alt="image" src="https://github.com/wtetsu/vscode-tempfile/assets/32426600/e8a3c63b-5fb1-4bb5-b120-f5ca25cb00b2">

I am willing to contribute to fixing this issue. Please let me know.

**Comment by wtetsu** [comment]
Thank you for your suggestion.

Implementing a feature to delete all created temporary files at once is impractical due to technical reasons. Users can set the `tempfile.newFilePath` configuration to any location, making an all-deletion command risky.

Instead, I recommend setting `tempfile.newFilePath` to a specific folder in your workspace, like `{{wsdir}}/.tempfile/{{YYYY}}{{MM}}{{DD}}_{{HH}}{{mm}}{{ss}}{{SSS}}.md`. This way, you can delete all temporary files by simply removing one folder.

**Comment by devangtomar** [comment]
This seems promising indeed. I'm going to test out this functionality and will provide feedback soon! 🙃

**Comment by devangtomar** [comment]
@wtetsu Yes the setting worked. Closing the issue :)
